language: java
jdk:
  - openjdk17

branches:
  only:
    - main
    
before_install:
  - chmod +x gradlew
  
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    
script:
  - ./gradlew clean build

# before_deploy:
#   - zip -r springboot-webservice3-project *
#   - mkdir -p deploy
#   - mv springboot-webservice3-project.zip deploy/springboot-webservice3-project.zip

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springboot-webservice3-project.zip # deploy로 zip파일 이동.
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-hj
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-hj
    key: springboot-webservice3-project.zip
    bundle_type: zip
    application: freelec-springboot3-webservice
    deployment_group: freelec-springboot3-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main
      
# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - 'toyu7870@naver.com'
