language: java
jdk:
  - openjdk17

branches:
  only:
    - main
    
before_install:
  - chmod +x gradlew
  
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    
script:
  - ./gradlew clean build

before_deploy:
  - zip -r springboot-webservice3-project *
  - mkdir -p deploy
  - mv springboot-webservice3-project.zip deploy/springboot-webservice3-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-hj
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - 'toyu7870@naver.com'
